import { Product } from "@/types/product";
import { v4 as uuidv4 } from "uuid";

export const madeForYou: Product[] = [
  {
    id: uuidv4(),
    title: "Procreate Chain and Jewelry Brushes by Vegalia",
    productImage: "/made-for-you/card-1.jpg",
    user: "Vegalia",
    userPhoto: "/made-for-you/profile-01.jpg",
    userLink: "#",
    stars: 5,
    totalReviews: 21,
    price: 12,
  },
  {
    id: uuidv4(),
    title: "Paper Pack",
    productImage: "/made-for-you/card-2.jpg",
    user: "MaxPacks - Brushes for Procreate",
    userPhoto: "/made-for-you/profile-02.jpg",
    userLink: "#",
    stars: 5,
    totalReviews: 125,
    price: 15,
  },
  {
    id: uuidv4(),
    title: "Instagram Close Friends Family",
    productImage: "/made-for-you/card-3.jpg",
    user: "Chris Johnson",
    userPhoto: "/made-for-you/profile-03.jpg",
    userLink: "#",
    stars: 5,
    totalReviews: 231,
    price: 10,
  },
  {
    id: uuidv4(),
    title: "Fangy Business Issue#1 (English)",
    productImage: "/made-for-you/card-4.jpg",
    user: "Labro",
    userPhoto: "/made-for-you/profile-04.jpg",
    userLink: "#",
    stars: 4.9,
    totalReviews: 1,
    price: 0,
  },
  {
    id: uuidv4(),
    title: "Small Bets - Lifetime Membership",
    productImage: "/made-for-you/card-5.jpg",
    user: "Daniel Vassallo",
    userPhoto: "/made-for-you/profile-05.jpg",
    userLink: "#",
    stars: 5,
    totalReviews: 151,
    price: 375,
  },
  {
    id: uuidv4(),
    title: "ChordieApp for Mac OS X",
    productImage: "/made-for-you/card-6.jpg",
    user: "Matkat Music",
    userPhoto: "/made-for-you/profile-06.jpg",
    userLink: "#",
    stars: 5,
    totalReviews: 312,
    price: 20,
  },
];
